import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapClient from "@/js/bootstrapClient";
import "bootstrap/dist/css/bootstrap.css";
import RootProvider from "./_redux/Provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <RootProvider>

        {children}
        <BootstrapClient />
      </RootProvider>

      </body>
    </html>
  );
}
